// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP _flipChoice_d0CriterionShortcut(SEXP question_designSEXP, SEXP partial_info_matrixSEXP, SEXP alternatives_per_questionSEXP);
SEXP _flipChoice_d0PartialInfoMatrix(SEXP coded_designSEXP, SEXP n_questionsSEXP, SEXP questionSEXP, SEXP alternatives_per_questionSEXP);
SEXP _flipChoice_choiceProbabilities(SEXP question_designSEXP, SEXP priorSEXP);
SEXP _flipChoice_dPCriterionShortcut(SEXP question_designSEXP, SEXP priorSEXP, SEXP partial_info_matrixSEXP, SEXP alternatives_per_questionSEXP);
SEXP _flipChoice_dPPartialInfoMatrix(SEXP coded_designSEXP, SEXP priorSEXP, SEXP n_questionsSEXP, SEXP questionSEXP, SEXP alternatives_per_questionSEXP);
SEXP _flipChoice_setLevel(SEXP question_designSEXP, SEXP row_indexSEXP, SEXP attribute_indexSEXP, SEXP lvlSEXP, SEXP levels_per_attributeSEXP, SEXP start_indicesSEXP);
SEXP _flipChoice_setLevelAllRows(SEXP question_designSEXP, SEXP attribute_indexSEXP, SEXP lvlSEXP, SEXP levels_per_attributeSEXP, SEXP start_indicesSEXP);
SEXP _flipChoice_getLevel(SEXP question_designSEXP, SEXP row_indexSEXP, SEXP attribute_indexSEXP, SEXP levels_per_attributeSEXP, SEXP start_indicesSEXP);

R_CallMethodDef callMethods[]  = {
  {"_flipChoice_d0CriterionShortcut", (DL_FUNC) &_flipChoice_d0CriterionShortcut, 3},
  {"_flipChoice_d0PartialInfoMatrix", (DL_FUNC) &_flipChoice_d0PartialInfoMatrix, 4},
  {"_flipChoice_choiceProbabilities", (DL_FUNC) &_flipChoice_choiceProbabilities, 2},
  {"_flipChoice_dPCriterionShortcut", (DL_FUNC) &_flipChoice_dPCriterionShortcut, 4},
  {"_flipChoice_dPPartialInfoMatrix", (DL_FUNC) &_flipChoice_dPPartialInfoMatrix, 5},
  {"_flipChoice_setLevel", (DL_FUNC) &_flipChoice_setLevel, 6},
  {"_flipChoice_setLevelAllRows", (DL_FUNC) &_flipChoice_setLevelAllRows, 5},
  {"_flipChoice_getLevel", (DL_FUNC) &_flipChoice_getLevel, 5},
  {NULL, NULL, 0}
};

void R_init_flipChoice(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, TRUE);
}

