# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d0CriterionShortcutRcpp <- function(question_design, partial_info_matrix, alternatives_per_question) {
    .Call(`_flipChoice_d0CriterionShortcutRcpp`, question_design, partial_info_matrix, alternatives_per_question)
}

